version: '2'
services:
  ao-basket-api:
    build: .
    ports:
      - 5001:5001
    volumes:
      - .:/usr/src/app
    links:
      - ao-mongo
    depends_on:
      - ao-mongo
  ao-mongo:
    image: mongo:latest
    container_name: "ao-basket-mongo"
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
